package com.springboot.demo.model;

import java.time.LocalDate;

import com.springboot.demo.enums.EmployeeAccessStatusEnum;

import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.OneToOne;

@Entity
public class Employee {

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO) // Auto generated by Hibernate
	private Long id;

	private String name; // varchar(255) in mysql
	private String jobTitle;
	private LocalDate createdAt;
	
	//findByJobTitleANdAccessType(jobTitle,accessType): Employee
	@Enumerated(EnumType.STRING)
	private EmployeeAccessStatusEnum accessType; //GRANTED, DENIED, PENDING
	
	
	@OneToOne
	private User user;
	
	@ManyToOne
	private Admin admin; 
	
	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getJobTitle() {
		return jobTitle;
	}

	public void setJobTitle(String jobTitle) {
		this.jobTitle = jobTitle;
	}

	public LocalDate getCreatedAt() {
		return createdAt;
	}

	public void setCreatedAt(LocalDate createdAt) {
		this.createdAt = createdAt;
	}

	public User getUser() {
		return user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	
	public Admin getAdmin() {
		return admin;
	}

	public void setAdmin(Admin admin) {
		this.admin = admin;
	}

	public EmployeeAccessStatusEnum getAccessType() {
		return accessType;
	}

	public void setAccessType(EmployeeAccessStatusEnum accessType) {
		this.accessType = accessType;
	}

}